version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: portfoliosite_frontend
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "yarn dev"
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
