version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: portfoliosite_frontend
    volumes:
      - ./frontend:/usr/src/app
      - node_modules_volume:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: sh -c "yarn dev"
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules_volume:
